# Dockerfile
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

RUN apk add --no-cache bash curl \
    && curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_x86_64.tar.gz \
    | tar -xz -C /usr/local/bin \
    && chmod +x /usr/local/bin/grpcurl

COPY blockchain-core/target/blockchain-core-1.0-SNAPSHOT.jar full.jar

CMD ["java", "-jar", "full.jar", "full", "full-node-a"]
