services:
  bootstrap:
    build:
      context: .
      dockerfile: Dockerfile.bootstrap
    container_name: bootstrap-node
    ports:
      - "50051:50051"
    networks:
      - blockchain-net

  full-node-a:
    build:
      context: .
      dockerfile: Dockerfile.full
    container_name: full-node-a
    volumes:
      - fullnode_a_data:/data
    ports:
      - "9090:9090"
    depends_on:
      - bootstrap
    networks:
      - blockchain-net

  full-node-b:
    build:
      context: .
      dockerfile: Dockerfile.fullb
    container_name: full-node-b
    volumes:
      - fullnode_b_data:/data
    ports:
      - "9091:9090"
    depends_on:
      - bootstrap
      - full-node-a
    networks:
      - blockchain-net

  light-node-a:
    build:
      context: .
      dockerfile: Dockerfile.light
    container_name: light-node-a
    ports:
      - "8081:8081"
    depends_on:
      - bootstrap
      - full-node-a
      - full-node-b
    networks:
      - blockchain-net

  light-node-b:
    build:
      context: .
      dockerfile: Dockerfile.light
    container_name: light-node-b
    ports:
      - "8082:8082"
    depends_on:
      - bootstrap
      - full-node-a
      - full-node-b
    networks:
      - blockchain-net

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: grpc-server
    ports:
      - "9595:9595"
    depends_on:
      - bootstrap
      - full-node-a
      - full-node-b
    networks:
      - blockchain-net

volumes:
  fullnode_a_data:
  fullnode_b_data:

networks:
  blockchain-net:
    driver: bridge
