FROM alpine:3.18

RUN apk add --no-cache curl bash \
    && curl -L https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_x86_64.tar.gz \
    | tar -xz -C /usr/local/bin \
    && chmod +x /usr/local/bin/grpcurl

WORKDIR /app/protos
COPY grpc-common/src/main/proto/ .

ENTRYPOINT ["tail", "-f", "/dev/null"]
